id: IA0330B29
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:54:18+00:00'
last_modified: '2022-06-08T13:59:54.742790+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18489
  title: ལས་བྱང་ཚོར་བ་རང་གྲོལ་གྱི་སྙིང་པོའི་རྣམ་བཤད་རིམ་གཉིས་གསལ་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C1DD:
      image_group_id: I1KG18507
      title: ''
      total_pages: 390
      order: 1
      base_file: C1DD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
