id: P010492
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18489
  title: ལས་བྱང་ཚོར་བ་རང་གྲོལ་གྱི་སྙིང་པོའི་རྣམ་བཤད་རིམ་གཉིས་གསལ་བྱེད།
  author: ''
  volumes:
    2e7166977e18427387eab1fff37ae985:
      image_group_id: I1KG18507
      title: ''
      volume_number: 1
      total_pages: 390
      base_file: v001.txt
